@startuml
title Sample of Robustness diagram


usecase ドローンの予約

actor 利用ユーザ
boundary ターミナル
control ドローン予約
control アカウントは存在するか
control 機体に空きがあるか
control ドローンのロック
entity 予約
entity ユーザアカウント
entity ドローン

利用ユーザ -> ターミナル
ターミナル -> ドローン予約 : API呼び出し
ドローン予約 -> アカウントは存在するか
アカウントは存在するか -> 機体に空きがあるか : はい
アカウントは存在するか -- ユーザアカウント
アカウントは存在するか -> ターミナル : いいえ
機体に空きがあるか -> ターミナル : いいえ
機体に空きがあるか -> ドローンのロック : はい
ドローンのロック -- ドローン
ドローンのロック -> 予約
@enduml